targetInstance: ${TEST_URL:http://localhost:4550}
jwt_test_secret: ${JWT_SECRET:a-very-long-and-boring-secret-key}
backend-encryption-key: ${DB_ENCRYPTION_KEY:ThisIsATestKeyForEncryption}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#Application specific properties
api-error-messages:
  bad_request: Invalid Request
  created: Successfully created
  updated: Successfully updated
  accepted: Success
  deleted: Successfully deleted
  internal_error: Unknown error occurred
api-required-header-keys:
  co-relationid: X-Correlation-Id
api-schema-file:
    submitanswer-schema: JsonSchema/submitAnswersSchema.json
api-version-number: 1
api-config-params.number_of_days_limit: ${NUMBER_OF_DAYS_LIMIT:90}

#Application specific unit test properties
unit-test:
  api-urls:
    submit_answer: /pcq/backend/submitAnswers
security:
  jwt:
    header: Authorization
    prefix: Bearer
  db:
    allow_delete_record: ${DB_ALLOW_DELETE_RECORD:true}
idam:
  s2s-auth:
    url: ${TEST_S2S_URL:http://localhost:4502}
    secret-cs: ${S2S_CS_SECRET:AAAAAAAAAAAAAAAA}
    name-cs: ${S2S_CS_NAME:pcq_consolidation_service}

authorised.services: pcq_consolidation_service,reform_scan_blob_router

storage:
  url: ${STORAGE_URL:http://0.0.0.0:10000}
  blob_pcq_container: ${STORAGE_BLOB_PCQ_CONTAINER:pcq}

logging:
  level:
    root: INFO
    uk.gov.hmcts.reform.pcqbackend: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PCQ_DB_HOST:localhost}:${PCQ_DB_PORT:5432}/${PCQ_DB_NAME:pcq}${PCQ_DB_CONN_OPTIONS:}
    username: ${PCQ_DB_USERNAME:pcquser}
    password: ${PCQ_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: PCQHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
      data-source-properties:
        socketTimeout: 8
