version: '2.1'

services:
  pcq-backend:
    build:
      context: .
    image: hmctspublic.azurecr.io/pcq/backend
    environment:
      # database configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pcq-database:5432/${PCQ_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${PCQ_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PCQ_DB_PASSWORD}
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
      # PGP Encryption configuration
      - DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - pcq-database

  pcq-database:
    container_name: pcq-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${PCQ_DB_USERNAME}
      POSTGRES_PASSWORD: ${PCQ_DB_PASSWORD}
      POSTGRES_DB: ${PCQ_DB_NAME}
    ports:
      - 5050:5432
    volumes:
      - pcq-database-data:/var/lib/postgresql/data

volumes:
  pcq-database-data:
